### ISSUE TITLE
There are no known links in ListofRickRolls.txt 

### ISSUE THREAD

**Issue by Mario675** [Rick-Roll-Link-Checker/Rick-Roll-Link-Checker#2]
### Solution:
- Fill the List of Rick Rolls.txt

**Comment by DamnUi** [comment]
There is one but i just dont know how to get it into text form

**Comment by DamnUi** [comment]
http://rickrolldb.com/

**Comment by DamnUi** [comment]
after a bit of searching i found it
https://rickrolldb.com/ricklist.txt

**Comment by DamnUi** [comment]
Thought this isnt the end we need to write a lot more in it for full filtering.
